insert into public.categories (name, slug, description, icon_name, accent_color, sort_order, is_published) values
('Hình ảnh', 'hinh-anh', 'Công cụ xử lý, nén, chuyển đổi và tối ưu hình ảnh hàng loạt.', 'Images', '#0058be', 10, true),
('PDF & tài liệu', 'pdf-tai-lieu', 'Tự động hóa thao tác với PDF, tài liệu và biểu mẫu.', 'FileText', '#ba1a1a', 20, true),
('Excel & dữ liệu', 'excel-du-lieu', 'Gộp, làm sạch, đối soát và trích xuất dữ liệu.', 'Table2', '#10b981', 30, true),
('Video & âm thanh', 'video-am-thanh', 'Công cụ phụ đề, media và xử lý nội dung đa phương tiện.', 'Video', '#924700', 40, true),
('Tự động hóa', 'tu-dong-hoa', 'Tool tự động thao tác lặp lại và quy trình nội bộ.', 'Bot', '#2170e4', 50, true),
('Công cụ hệ thống', 'cong-cu-he-thong', 'Tiện ích quản lý file, thư mục và môi trường Windows.', 'Settings', '#545f73', 60, true),
('Doanh nghiệp', 'doanh-nghiep', 'Giải pháp phục vụ bán hàng, kế toán và vận hành.', 'Briefcase', '#b75b00', 70, true)
on conflict (slug) do nothing;

with category_map as (
  select slug, id from public.categories
)
insert into public.tools (
  category_id, name, slug, short_description, description_markdown, price_type, price_vnd, old_price_vnd,
  version, license_text, compatibility, file_size, language_support, badge, primary_cta_label,
  primary_cta_type, features, system_requirements, changelog, faq, seo_title, seo_description,
  is_featured, is_published, sort_order, published_at
)
values
((select id from category_map where slug='hinh-anh'), 'Batch Image Studio', 'batch-image-studio', 'Xử lý ảnh hàng loạt: nén, đổi định dạng, resize và đóng dấu trong vài giây.', 'Batch Image Studio dành cho shop online, designer và đội vận hành cần xử lý nhiều ảnh mỗi ngày. Công cụ chạy trên Windows, tối ưu thao tác kéo thả và preset.', 'fixed', 599000, 799000, '2.4.0', 'Bản quyền trọn đời cho 1 máy', array['Windows 10','Windows 11'], '84 MB', array['Tiếng Việt','English'], 'Bán chạy', 'Yêu cầu báo giá', 'contact', '[{"text":"Resize, watermark và convert hàng loạt"},{"text":"Preset cho sàn thương mại điện tử"},{"text":"Xuất log xử lý sau mỗi phiên"}]', '[{"text":"Windows 10/11 64-bit"},{"text":"RAM tối thiểu 4GB"},{"text":"Dung lượng trống 300MB"}]', '[{"text":"2.4.0: Thêm preset WebP và tối ưu tốc độ nén"}]', '[{"question":"Có cần Internet để chạy không?","answer":"Không, các thao tác chính chạy offline trên máy Windows."}]', 'Batch Image Studio - Tool xử lý ảnh hàng loạt', 'Nén, resize, watermark và chuyển đổi ảnh hàng loạt trên Windows.', true, true, 10, now()),
((select id from category_map where slug='pdf-tai-lieu'), 'PDF Workflow Pro', 'pdf-workflow-pro', 'Trộn, chia nhỏ, bảo mật và trích xuất dữ liệu từ nhiều file PDF tự động.', 'PDF Workflow Pro giúp văn phòng xử lý tài liệu lặp lại theo batch, phù hợp cho kế toán, hành chính và đội nhập liệu.', 'contact', null, null, '1.8.0', 'Theo gói triển khai', array['Windows 10','Windows 11'], '120 MB', array['Tiếng Việt'], null, 'Tư vấn', 'contact', '[{"text":"Gộp và tách PDF theo quy tắc"},{"text":"Đặt mật khẩu hoặc watermark"},{"text":"Trích xuất bảng ra CSV"}]', '[{"text":"Windows 10/11"},{"text":"RAM 4GB trở lên"}]', '[]', '[{"question":"Có tùy chỉnh quy trình riêng không?","answer":"Có, chúng tôi có thể cấu hình theo mẫu tài liệu của bạn."}]', null, null, true, true, 20, now()),
((select id from category_map where slug='excel-du-lieu'), 'CSV Cleaner', 'csv-cleaner', 'Làm sạch, chuẩn hóa và phân tích CSV dung lượng lớn không cần mở Excel.', 'CSV Cleaner hỗ trợ loại dòng trùng, chuẩn hóa encoding, tách cột, map dữ liệu và xuất báo cáo kiểm tra.', 'fixed', 499000, null, '3.1.2', '1 PC', array['Windows 10','Windows 11'], '45 MB', array['Tiếng Việt'], 'Bán chạy', 'Mua ngay', 'contact', '[{"text":"Xử lý file CSV lớn"},{"text":"Chuẩn hóa Unicode và dấu tiếng Việt"},{"text":"Preview lỗi trước khi xuất"}]', '[{"text":"RAM khuyến nghị 8GB cho file lớn"}]', '[]', '[]', null, null, true, true, 30, now()),
((select id from category_map where slug='video-am-thanh'), 'Subtitle Studio', 'subtitle-studio', 'Tạo, chỉnh và đồng bộ phụ đề video nhanh cho đội nội dung.', 'Subtitle Studio hỗ trợ SRT/VTT, chỉnh thời gian hàng loạt và kiểm tra lỗi phụ đề trước khi xuất.', 'fixed', 399000, null, '1.5.0', '1 PC', array['Windows 10','Windows 11'], '66 MB', array['Tiếng Việt'], null, 'Yêu cầu tư vấn', 'contact', '[{"text":"Chỉnh lệch thời gian hàng loạt"},{"text":"Xuất SRT và VTT"},{"text":"Kiểm tra dòng quá dài"}]', '[{"text":"Windows 10/11"}]', '[]', '[]', null, null, false, true, 40, now()),
((select id from category_map where slug='excel-du-lieu'), 'Excel Data Merger', 'excel-data-merger', 'Gộp hàng trăm file Excel thành một báo cáo duy nhất chỉ với một cú nhấp.', 'Công cụ dành cho kế toán và vận hành cần gom file từ nhiều chi nhánh, chuẩn hóa sheet và xuất báo cáo tổng.', 'fixed', 499000, null, '2.2.1', '1 PC', array['Windows 10','Windows 11'], '52 MB', array['Tiếng Việt'], null, 'Mua ngay', 'contact', '[{"text":"Gộp nhiều workbook"},{"text":"Mapping cột bằng giao diện"},{"text":"Xuất báo cáo lỗi"}]', '[{"text":"Cần Microsoft Excel hoặc engine đọc XLSX tích hợp"}]', '[]', '[]', null, null, false, true, 50, now()),
((select id from category_map where slug='cong-cu-he-thong'), 'File Renamer Pro', 'file-renamer-pro', 'Đổi tên hàng loạt tệp tin theo quy tắc thông minh, hỗ trợ regex và metadata.', 'File Renamer Pro giúp chuẩn hóa thư viện file, ảnh sản phẩm và tài liệu nội bộ.', 'fixed', 199000, null, '1.9.0', '1 PC', array['Windows 10','Windows 11'], '30 MB', array['Tiếng Việt'], null, 'Mua ngay', 'contact', '[{"text":"Preview tên mới trước khi đổi"},{"text":"Hỗ trợ regex"},{"text":"Undo phiên đổi tên gần nhất"}]', '[{"text":"Windows 10/11"}]', '[]', '[]', null, null, false, true, 60, now()),
((select id from category_map where slug='doanh-nghiep'), 'Invoice XML Toolkit', 'invoice-xml-toolkit', 'Đọc, kiểm tra và tổng hợp hóa đơn XML cho kế toán doanh nghiệp.', 'Bộ công cụ hỗ trợ tổng hợp hóa đơn điện tử, kiểm tra dữ liệu và xuất bảng Excel theo mẫu.', 'contact', null, null, '1.2.0', 'Theo số máy', array['Windows 10','Windows 11'], '74 MB', array['Tiếng Việt'], null, 'Yêu cầu báo giá', 'contact', '[{"text":"Đọc XML hóa đơn điện tử"},{"text":"Xuất bảng kê theo mẫu"},{"text":"Cảnh báo dữ liệu thiếu"}]', '[{"text":"Windows 10/11"}]', '[]', '[]', null, null, true, true, 70, now()),
((select id from category_map where slug='hinh-anh'), 'Seller Media Factory', 'seller-media-factory', 'Tạo bộ ảnh sản phẩm chuẩn sàn, watermark và khung thương hiệu cho seller.', 'Công cụ dành cho đội bán hàng online cần tạo ảnh đồng bộ nhanh theo template.', 'contact', null, null, '1.0.0', 'Tùy chỉnh', array['Windows 10','Windows 11'], '92 MB', array['Tiếng Việt'], null, 'Tư vấn', 'contact', '[{"text":"Template theo thương hiệu"},{"text":"Watermark và khung ảnh"},{"text":"Xuất nhiều kích thước"}]', '[{"text":"Windows 10/11"}]', '[]', '[]', null, null, false, true, 80, now()),
((select id from category_map where slug='tu-dong-hoa'), 'Folder Automator', 'folder-automator', 'Theo dõi thư mục và tự động đổi tên, di chuyển, nén hoặc xuất báo cáo file.', 'Folder Automator xử lý luồng file đến liên tục cho team vận hành.', 'fixed', 299000, null, '2.0.0', '1 PC', array['Windows 10','Windows 11'], '38 MB', array['Tiếng Việt'], null, 'Mua ngay', 'contact', '[{"text":"Theo dõi thư mục realtime"},{"text":"Rule kéo thả dễ dùng"},{"text":"Log mọi thao tác"}]', '[{"text":"Windows 10/11"}]', '[]', '[]', null, null, false, true, 90, now()),
((select id from category_map where slug='hinh-anh'), 'Image Compressor', 'image-compressor', 'Giảm dung lượng ảnh hàng loạt mà vẫn giữ chất lượng hiển thị tốt.', 'Image Compressor phù hợp khi cần tối ưu ảnh website, ảnh sản phẩm và file gửi khách hàng.', 'free', null, null, '1.1.0', 'Miễn phí', array['Windows 10','Windows 11'], '26 MB', array['Tiếng Việt'], null, 'Tư vấn', 'contact', '[{"text":"Nén JPG/PNG/WebP"},{"text":"So sánh dung lượng trước sau"},{"text":"Không cần Internet"}]', '[{"text":"Windows 10/11"}]', '[]', '[]', null, null, false, true, 100, now()),
((select id from category_map where slug='excel-du-lieu'), 'OCR Data Extractor', 'ocr-data-extractor', 'Trích xuất dữ liệu từ ảnh, scan và biểu mẫu thành bảng kiểm tra được.', 'Giải pháp OCR tùy chỉnh cho mẫu chứng từ, đơn hàng và phiếu nội bộ.', 'contact', null, null, '1.0.0', 'Theo dự án', array['Windows 10','Windows 11'], '160 MB', array['Tiếng Việt'], null, 'Yêu cầu tư vấn', 'contact', '[{"text":"Nhận diện mẫu biểu"},{"text":"Xuất Excel/CSV"},{"text":"Kiểm tra thủ công trước khi chốt"}]', '[{"text":"Windows 11 khuyến nghị"}]', '[]', '[]', null, null, false, true, 110, now()),
((select id from category_map where slug='doanh-nghiep'), 'Profit Reconciler', 'profit-reconciler', 'Đối soát doanh thu, phí sàn và lợi nhuận theo từng đơn hàng.', 'Profit Reconciler giúp seller nhập dữ liệu từ nhiều nguồn để đối soát và phát hiện lệch phí.', 'contact', null, null, '1.0.0', 'Theo dự án', array['Windows 10','Windows 11'], '80 MB', array['Tiếng Việt'], null, 'Yêu cầu báo giá', 'contact', '[{"text":"Đối soát nhiều nguồn dữ liệu"},{"text":"Báo cáo lệch phí"},{"text":"Dashboard Excel xuất sẵn"}]', '[{"text":"Windows 10/11"}]', '[]', '[]', null, null, true, true, 120, now())
on conflict (slug) do nothing;

insert into public.services (title, slug, short_description, description_markdown, icon_name, price_label, features, process_steps, faq, is_featured, is_published, sort_order)
values
('Custom Tool Excel & Kế toán', 'custom-tool-excel-ke-toan', 'Thiết kế công cụ Excel/Windows theo nghiệp vụ kế toán riêng của doanh nghiệp.', 'Chúng tôi phân tích file mẫu, quy trình hiện tại và xây dựng tool giúp giảm thao tác lặp lại cho kế toán.', 'Table2', 'Liên hệ báo giá', '[{"text":"Chuẩn hóa dữ liệu đầu vào"},{"text":"Xuất báo cáo theo mẫu"},{"text":"Hỗ trợ bàn giao và chỉnh sửa"}]', '[{"text":"Khảo sát quy trình"},{"text":"Làm prototype"},{"text":"Bàn giao và hướng dẫn"}]', '[{"question":"Có nhận file mẫu bảo mật không?","answer":"Có, dữ liệu chỉ dùng để phân tích nghiệp vụ và có thể ký NDA nếu cần."}]', true, true, 10),
('Phát triển phần mềm Windows', 'phat-trien-phan-mem-windows', 'Xây dựng phần mềm EXE nội bộ, chạy ổn định trên Windows 10/11.', 'Dịch vụ phù hợp cho công cụ vận hành, nhập liệu, xử lý file và tích hợp API nội bộ.', 'MonitorCog', 'Liên hệ báo giá', '[{"text":"Giao diện dễ dùng"},{"text":"Cài đặt dạng EXE"},{"text":"Bảo trì sau bàn giao"}]', '[{"text":"Chốt phạm vi"},{"text":"Thiết kế UI"},{"text":"Phát triển và test"}]', '[]', true, true, 20),
('Tự động hóa quy trình RPA', 'tu-dong-hoa-quy-trinh-rpa', 'Tự động hóa thao tác lặp lại trên trình duyệt, phần mềm và file nội bộ.', 'Giảm thời gian nhập liệu, copy paste và kiểm tra thủ công bằng bot RPA theo kịch bản.', 'Bot', 'Liên hệ báo giá', '[{"text":"Tự động đăng nhập và nhập liệu"},{"text":"Theo dõi lỗi rõ ràng"},{"text":"Có log vận hành"}]', '[{"text":"Ghi nhận thao tác"},{"text":"Xây dựng bot"},{"text":"Chạy thử với dữ liệu thật"}]', '[]', true, true, 30),
('Xử lý và thu thập dữ liệu', 'xu-ly-va-thu-thap-du-lieu', 'Thu thập, làm sạch và xuất dữ liệu từ website, file hoặc API.', 'Giải pháp cho đội cần dữ liệu có cấu trúc phục vụ báo cáo, bán hàng hoặc vận hành.', 'DatabaseZap', 'Liên hệ báo giá', '[{"text":"Scraping có kiểm soát"},{"text":"Làm sạch dữ liệu"},{"text":"Xuất Excel/CSV/JSON"}]', '[{"text":"Xác định nguồn dữ liệu"},{"text":"Thiết kế bộ lọc"},{"text":"Bàn giao dữ liệu và tool"}]', '[]', false, true, 40),
('Hệ thống quản lý nội bộ', 'he-thong-quan-ly-noi-bo', 'Thiết kế hệ thống quản lý quy trình, khách hàng, đơn hàng hoặc kho nội bộ.', 'Xây dựng web app hoặc phần mềm nội bộ nhẹ, tập trung đúng quy trình doanh nghiệp.', 'BriefcaseBusiness', 'Liên hệ báo giá', '[{"text":"Phân quyền nội bộ"},{"text":"Báo cáo vận hành"},{"text":"Dữ liệu tập trung"}]', '[{"text":"Phân tích nghiệp vụ"},{"text":"Thiết kế màn hình"},{"text":"Triển khai từng giai đoạn"}]', '[]', false, true, 50),
('Tích hợp API và nền tảng', 'tich-hop-api-va-nen-tang', 'Kết nối phần mềm với sàn, CRM, kế toán, Zalo, Telegram hoặc hệ thống sẵn có.', 'Dịch vụ giúp dữ liệu đi đúng nơi, giảm nhập liệu lại và hạn chế sai sót.', 'Cable', 'Liên hệ báo giá', '[{"text":"Kết nối API"},{"text":"Đồng bộ dữ liệu"},{"text":"Cảnh báo lỗi tích hợp"}]', '[{"text":"Kiểm tra tài liệu API"},{"text":"Xây dựng connector"},{"text":"Theo dõi sau triển khai"}]', '[]', false, true, 60)
on conflict (slug) do nothing;

insert into public.content_blocks (page_key, section_key, title, content, sort_order, is_published)
values
('home', 'hero', 'Cửa hàng phần mềm', '{"description":"Các công cụ Windows giúp tự động hóa công việc, xử lý dữ liệu và tiết kiệm thời gian.","badges":["Phần mềm chính chủ","Cập nhật miễn phí","Hỗ trợ tiếng Việt","Tư vấn triển khai"]}', 10, true),
('home', 'trust', 'Vì sao chọn ToolBox Việt', '{"items":["Giao diện rõ ràng, dễ dùng cho người Việt","Có thể tùy chỉnh theo quy trình thật","Dữ liệu và bảo mật được ưu tiên","Hỗ trợ sau bàn giao"]}', 20, true),
('services', 'hero', 'Dịch vụ & Giải pháp Tùy chỉnh', '{"description":"Giải pháp tự động hóa tùy chỉnh và phát triển phần mềm chuyên biệt cho doanh nghiệp của bạn.","badges":["Thiết kế theo yêu cầu","Tối ưu quy trình","Hỗ trợ tận tâm"]}', 10, true),
('contact', 'copy', 'Liên hệ tư vấn', '{"description":"Để lại nhu cầu của bạn, đội ngũ kỹ thuật sẽ phản hồi với hướng triển khai phù hợp."}', 10, true),
('footer', 'links', 'Footer', '{"columns":[{"title":"Liên kết","links":["Cửa hàng","Dịch vụ","Chính sách bảo mật","Điều khoản sử dụng"]}]}', 10, true),
('privacy', 'main', 'Chính sách bảo mật', '{"body":"ToolBox Việt chỉ thu thập thông tin cần thiết để tư vấn, báo giá và hỗ trợ khách hàng. Chúng tôi không bán dữ liệu cá nhân cho bên thứ ba."}', 10, true),
('terms', 'main', 'Điều khoản sử dụng', '{"body":"Khi sử dụng website, bạn đồng ý cung cấp thông tin chính xác khi gửi yêu cầu tư vấn và tuân thủ điều khoản sử dụng phần mềm được bàn giao."}', 10, true)
on conflict (page_key, section_key) do nothing;
